---
title: "Data Dictionary"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


 Data Name | Data Types | Description  |
-----------|:-----------|:-----------------------------------------------------:|
Team_name | character | The name of the team  |
Game_date | numeric   | The date of the game  | 
Season  | numeric   | The season of the game|
Period | numeric   | An NBA game is divided in 4 periods of 12 mins each. For example, a value for period = 1 refers to the first period (the first 12 mins of the game).|
Minutes_remaining | numeric | Have to do with the amount of time in minutes that remained to be played in a given period.|
Second_remaining | numeric | Have to do with the amount of time in seconds that remained to be played in a given period. |
Shot_made_flag | character | indicates whether a shot was made (y) or missed (n). |
Action_type | character | the basketball moves used by players, either to pass by defenders to gain access to the basket, or to get a clean pass to a teammate to score a two pointer or three pointer.|
short_type | character | indicates whether a shot is a 2-point field goal, or a 3-point field goal. |
shot_distance | numeric | distance to the basket (measured in feet). |
Opponent | numeric | The team that they playing against to | 
x | numeric | the court coordinates (measured in inches) where a shot occurred . |
y | numeric | the court coordinates (measured in inches) where a shot occurred . |

